<?php
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) { die(); }
$iblockId = (int)$arResult['IBLOCK_ID'];
$roleOptions = blackPatternJournalEnumOptions($iblockId, 'ROLE');
$themeOptions = blackPatternJournalEnumOptions($iblockId, 'THEME');
$authorIds = array_map('intval', (array)($arResult['PROPERTIES']['AUTHORS']['VALUE'] ?? []));
$article = blackPatternJournalArticleData($arResult, $iblockId, $roleOptions, $themeOptions, blackPatternJournalLoadAuthors($authorIds));
$author = $article['AUTHORS'][0] ?? null;
$authorPhoto = $author ? CFile::GetPath((int)$author['PREVIEW_PICTURE']) : '';
$cover = CFile::GetPath((int)($article['DETAIL_PICTURE'] ?: $article['PREVIEW_PICTURE']));
$relatedIds = array_map('intval', (array)($arResult['PROPERTIES']['RELATED_ARTICLES']['VALUE'] ?? []));
$related = blackPatternJournalRelatedArticles($article, $iblockId, $roleOptions, $themeOptions, $relatedIds, 3);
?>
<header class="article-header"><div class="wrap article-wrap"><nav class="article-crumbs" aria-label="Хлебные крошки"><a href="/journal/">Журнал</a><span>/</span><span><?= htmlspecialcharsbx($article['ROLE_NAMES'][0] ?? 'Материал'); ?></span></nav><div class="article-tags"><span class="journal-who"><span class="journal-dot <?= blackPatternJournalRoleClass($article); ?>"></span><?= htmlspecialcharsbx(implode(', ', $article['ROLE_NAMES'])); ?></span><?php foreach ($article['THEME_NAMES'] as $theme): ?><span class="article-tag"><?= htmlspecialcharsbx($theme); ?></span><?php endforeach; ?></div><h1><?= htmlspecialcharsbx($article['NAME']); ?></h1><p class="article-dek"><?= htmlspecialcharsbx($article['PREVIEW_TEXT']); ?></p><div class="article-byline"><?php if ($authorPhoto): ?><img class="article-avatar" src="<?= htmlspecialcharsbx($authorPhoto); ?>" alt="<?= htmlspecialcharsbx($author['NAME']); ?>"><?php else: ?><span class="article-avatar" aria-hidden="true"></span><?php endif; ?><div><?php if ($author): ?><div class="article-author-name"><?= htmlspecialcharsbx($author['NAME']); ?></div><div class="article-author-role"><?= htmlspecialcharsbx($author['POSITION']); ?></div><?php else: ?><div class="article-author-name">Black Pattern</div><?php endif; ?></div><div class="article-reading"><?= htmlspecialcharsbx($article['DATE_FORMATTED']); ?><?= $article['READING_TIME'] ? ' · ' . $article['READING_TIME'] . ' мин' : ''; ?></div></div></div><div class="wrap"><?php if ($cover): ?><img class="article-cover" src="<?= htmlspecialcharsbx($cover); ?>" alt="<?= htmlspecialcharsbx($article['NAME']); ?>"><?php else: ?><div class="journal-cover-placeholder article-cover-placeholder">ОБЛОЖКА МАТЕРИАЛА</div><?php endif; ?></div></header>
<article class="article-body"><div class="wrap article-wrap"><?= $article['DETAIL_TEXT'] ?: '<p>' . htmlspecialcharsbx($article['PREVIEW_TEXT']) . '</p>'; ?></div></article>
<?php if ($author): ?><aside class="article-author"><div><?php if ($authorPhoto): ?><img class="article-avatar" src="<?= htmlspecialcharsbx($authorPhoto); ?>" alt="<?= htmlspecialcharsbx($author['NAME']); ?>"><?php else: ?><span class="article-avatar" aria-hidden="true"></span><?php endif; ?></div><div><div class="article-author-name"><?= htmlspecialcharsbx($author['NAME']); ?></div><div class="article-author-role"><?= htmlspecialcharsbx($author['POSITION']); ?></div><p><?= htmlspecialcharsbx($author['PREVIEW_TEXT']); ?></p></div></aside><?php endif; ?>
<?php if ($related): ?><section class="journal-related"><div class="wrap"><h2>Читать дальше</h2><div class="journal-cards"><?php foreach ($related as $item): ?><a class="journal-card" href="<?= blackPatternJournalUrl($item['CODE']); ?>"><div class="journal-card-meta"><span class="journal-who"><span class="journal-dot <?= blackPatternJournalRoleClass($item); ?>"></span><?= htmlspecialcharsbx(implode(', ', $item['ROLE_NAMES'])); ?></span><?php if ($item['THEME_NAMES']): ?> · <?= htmlspecialcharsbx(implode(', ', $item['THEME_NAMES'])); ?><?php endif; ?></div><h2><?= htmlspecialcharsbx($item['NAME']); ?></h2><p><?= htmlspecialcharsbx($item['PREVIEW_TEXT']); ?></p><span class="journal-read">Читать<?= $item['READING_TIME'] ? ' · ' . $item['READING_TIME'] . ' мин' : ''; ?> →</span></a><?php endforeach; ?></div></div></section><?php endif; ?>
<section class="article-final-cta"><div class="wrap"><div class="article-final-inner"><?php $APPLICATION->IncludeFile('/local/include/journal/article-final-cta.php', [], ['MODE' => 'html', 'NAME' => 'Финальный призыв в статьях']); ?><div class="article-final-actions"><button class="btn btn-red" type="button" data-bp-modal-open="journal-diagnostic-modal">Записаться на диагностику →</button><a class="btn btn-glass" href="/journal/">Вернуться в журнал</a></div></div></div></section>
<dialog class="bp-modal" id="journal-diagnostic-modal" data-bp-modal aria-labelledby="journal-diagnostic-modal-title"><div class="bp-modal-card"><button class="bp-modal-close" type="button" data-bp-modal-close aria-label="Закрыть форму"><span aria-hidden="true"></span></button><h2 id="journal-diagnostic-modal-title">Записаться на диагностику</h2><?php if (\Bitrix\Main\Loader::includeModule('blackpattern.settings')): ?><?= \BlackPattern\Forms\FormRenderer::render('callback_short', ['SUBMIT_TEXT' => 'Записаться', 'CLASS' => 'bp-popup-form bp-form-compact', 'COMPACT' => 'Y']); ?><?php else: ?><p class="bp-modal-fallback">Форма временно недоступна.</p><?php endif; ?></div></dialog>
